<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_arm_length" value="0.1" />
    <xacro:property name="base_arm_weidth" value="0.1" />
    <xacro:property name="base_arm_hight"  value="0.02"/>
    <xacro:property name="forearm_radius"  value="0.02"/>
    <xacro:property name="forearm_length"  value="0.3" />
    <xacro:property name="hand_radius"     value="0.02"/>
    <xacro:property name="hand_length"     value="0.2" />
    

    <link name="robot_arm_base_link">
        <visual>
            <geometry>
                <box size="${base_arm_length} ${base_arm_weidth} ${base_arm_hight}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_arm_length} ${base_arm_weidth} ${base_arm_hight}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia  m="0.5" l="${2.0 * base_arm_length}" w="${2.0 * base_arm_weidth}" h="${2.0 * base_arm_hight}"
                            xyz="0 0 0" rpy="0 0 0" />
        
    </link>

    <link name="forearm_link">
        <visual>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2.0 * forearm_radius}" l="${2.0 * forearm_length}"
                                xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2.0 * hand_radius}" l="${2.0 * hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>




    <joint name="base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="robot_arm_base_link" />
        <origin xyz="${base_lenght/4.0} 0 ${base_hight + base_arm_hight / 2.0 }" rpy="0 0 0" />

    </joint>

    <joint name="base_forearm_joint" type="revolute">
        <parent link="robot_arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${base_arm_hight/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>
</robot>